// Code generated by MockGen. DO NOT EDIT.
// Source: ../interface/message/message.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/go-park-mail-ru/2025_2_Undefined/internal/transport/dto/chats"
	dto0 "github.com/go-park-mail-ru/2025_2_Undefined/internal/transport/dto/message"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockMessageUsecase is a mock of MessageUsecase interface.
type MockMessageUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockMessageUsecaseMockRecorder
}

// MockMessageUsecaseMockRecorder is the mock recorder for MockMessageUsecase.
type MockMessageUsecaseMockRecorder struct {
	mock *MockMessageUsecase
}

// NewMockMessageUsecase creates a new mock instance.
func NewMockMessageUsecase(ctrl *gomock.Controller) *MockMessageUsecase {
	mock := &MockMessageUsecase{ctrl: ctrl}
	mock.recorder = &MockMessageUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageUsecase) EXPECT() *MockMessageUsecaseMockRecorder {
	return m.recorder
}

// AddMessage mocks base method.
func (m *MockMessageUsecase) AddMessage(ctx context.Context, message dto0.CreateMessageDTO, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMessage", ctx, message, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMessage indicates an expected call of AddMessage.
func (mr *MockMessageUsecaseMockRecorder) AddMessage(ctx, message, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMessage", reflect.TypeOf((*MockMessageUsecase)(nil).AddMessage), ctx, message, userID)
}

// AddMessageJoinUsers mocks base method.
func (m *MockMessageUsecase) AddMessageJoinUsers(ctx context.Context, chatID uuid.UUID, users []dto.AddChatMemberDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMessageJoinUsers", ctx, chatID, users)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMessageJoinUsers indicates an expected call of AddMessageJoinUsers.
func (mr *MockMessageUsecaseMockRecorder) AddMessageJoinUsers(ctx, chatID, users interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMessageJoinUsers", reflect.TypeOf((*MockMessageUsecase)(nil).AddMessageJoinUsers), ctx, chatID, users)
}

// DeleteMessage mocks base method.
func (m *MockMessageUsecase) DeleteMessage(ctx context.Context, message dto0.DeleteMessageDTO, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMessage", ctx, message, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMessage indicates an expected call of DeleteMessage.
func (mr *MockMessageUsecaseMockRecorder) DeleteMessage(ctx, message, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessage", reflect.TypeOf((*MockMessageUsecase)(nil).DeleteMessage), ctx, message, userID)
}

// EditMessage mocks base method.
func (m *MockMessageUsecase) EditMessage(ctx context.Context, message dto0.EditMessageDTO, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditMessage", ctx, message, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditMessage indicates an expected call of EditMessage.
func (mr *MockMessageUsecaseMockRecorder) EditMessage(ctx, message, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditMessage", reflect.TypeOf((*MockMessageUsecase)(nil).EditMessage), ctx, message, userID)
}

// GetChatMessages mocks base method.
func (m *MockMessageUsecase) GetChatMessages(ctx context.Context, userID, chatID uuid.UUID, offset, limit int) ([]dto0.MessageDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatMessages", ctx, userID, chatID, offset, limit)
	ret0, _ := ret[0].([]dto0.MessageDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatMessages indicates an expected call of GetChatMessages.
func (mr *MockMessageUsecaseMockRecorder) GetChatMessages(ctx, userID, chatID, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatMessages", reflect.TypeOf((*MockMessageUsecase)(nil).GetChatMessages), ctx, userID, chatID, offset, limit)
}

// GetMessagesBySearch mocks base method.
func (m *MockMessageUsecase) GetMessagesBySearch(ctx context.Context, userID, chatID uuid.UUID, text string) ([]dto0.MessageDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesBySearch", ctx, userID, chatID, text)
	ret0, _ := ret[0].([]dto0.MessageDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesBySearch indicates an expected call of GetMessagesBySearch.
func (mr *MockMessageUsecaseMockRecorder) GetMessagesBySearch(ctx, userID, chatID, text interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesBySearch", reflect.TypeOf((*MockMessageUsecase)(nil).GetMessagesBySearch), ctx, userID, chatID, text)
}

// SubscribeConnectionToChats mocks base method.
func (m *MockMessageUsecase) SubscribeConnectionToChats(ctx context.Context, connectionID, userID uuid.UUID, chatsDTO []dto.ChatViewInformationDTO) <-chan dto0.WebSocketMessageDTO {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeConnectionToChats", ctx, connectionID, userID, chatsDTO)
	ret0, _ := ret[0].(<-chan dto0.WebSocketMessageDTO)
	return ret0
}

// SubscribeConnectionToChats indicates an expected call of SubscribeConnectionToChats.
func (mr *MockMessageUsecaseMockRecorder) SubscribeConnectionToChats(ctx, connectionID, userID, chatsDTO interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeConnectionToChats", reflect.TypeOf((*MockMessageUsecase)(nil).SubscribeConnectionToChats), ctx, connectionID, userID, chatsDTO)
}

// SubscribeUsersOnChat mocks base method.
func (m *MockMessageUsecase) SubscribeUsersOnChat(ctx context.Context, chatID uuid.UUID, members []dto.AddChatMemberDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeUsersOnChat", ctx, chatID, members)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubscribeUsersOnChat indicates an expected call of SubscribeUsersOnChat.
func (mr *MockMessageUsecaseMockRecorder) SubscribeUsersOnChat(ctx, chatID, members interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeUsersOnChat", reflect.TypeOf((*MockMessageUsecase)(nil).SubscribeUsersOnChat), ctx, chatID, members)
}
