// Code generated by MockGen. DO NOT EDIT.
// Source: ../interface/chats/chats.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	minio "github.com/go-park-mail-ru/2025_2_Undefined/internal/repository/minio"
	dto "github.com/go-park-mail-ru/2025_2_Undefined/internal/transport/dto/chats"
	dto0 "github.com/go-park-mail-ru/2025_2_Undefined/internal/transport/dto/utils"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockChatsUsecase is a mock of ChatsUsecase interface.
type MockChatsUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockChatsUsecaseMockRecorder
}

// MockChatsUsecaseMockRecorder is the mock recorder for MockChatsUsecase.
type MockChatsUsecaseMockRecorder struct {
	mock *MockChatsUsecase
}

// NewMockChatsUsecase creates a new mock instance.
func NewMockChatsUsecase(ctrl *gomock.Controller) *MockChatsUsecase {
	mock := &MockChatsUsecase{ctrl: ctrl}
	mock.recorder = &MockChatsUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatsUsecase) EXPECT() *MockChatsUsecaseMockRecorder {
	return m.recorder
}

// AddUsersToChat mocks base method.
func (m *MockChatsUsecase) AddUsersToChat(ctx context.Context, chatID, userID uuid.UUID, users []dto.AddChatMemberDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUsersToChat", ctx, chatID, userID, users)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUsersToChat indicates an expected call of AddUsersToChat.
func (mr *MockChatsUsecaseMockRecorder) AddUsersToChat(ctx, chatID, userID, users interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUsersToChat", reflect.TypeOf((*MockChatsUsecase)(nil).AddUsersToChat), ctx, chatID, userID, users)
}

// CreateChat mocks base method.
func (m *MockChatsUsecase) CreateChat(ctx context.Context, chatDTO dto.ChatCreateInformationDTO) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChat", ctx, chatDTO)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChat indicates an expected call of CreateChat.
func (mr *MockChatsUsecaseMockRecorder) CreateChat(ctx, chatDTO interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChat", reflect.TypeOf((*MockChatsUsecase)(nil).CreateChat), ctx, chatDTO)
}

// DeleteChat mocks base method.
func (m *MockChatsUsecase) DeleteChat(ctx context.Context, userId, chatId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChat", ctx, userId, chatId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChat indicates an expected call of DeleteChat.
func (mr *MockChatsUsecaseMockRecorder) DeleteChat(ctx, userId, chatId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChat", reflect.TypeOf((*MockChatsUsecase)(nil).DeleteChat), ctx, userId, chatId)
}

// GetChatAvatars mocks base method.
func (m *MockChatsUsecase) GetChatAvatars(ctx context.Context, userId uuid.UUID, chatIDs []uuid.UUID) (map[string]*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatAvatars", ctx, userId, chatIDs)
	ret0, _ := ret[0].(map[string]*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatAvatars indicates an expected call of GetChatAvatars.
func (mr *MockChatsUsecaseMockRecorder) GetChatAvatars(ctx, userId, chatIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatAvatars", reflect.TypeOf((*MockChatsUsecase)(nil).GetChatAvatars), ctx, userId, chatIDs)
}

// GetChats mocks base method.
func (m *MockChatsUsecase) GetChats(ctx context.Context, userId uuid.UUID) ([]dto.ChatViewInformationDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChats", ctx, userId)
	ret0, _ := ret[0].([]dto.ChatViewInformationDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChats indicates an expected call of GetChats.
func (mr *MockChatsUsecaseMockRecorder) GetChats(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChats", reflect.TypeOf((*MockChatsUsecase)(nil).GetChats), ctx, userId)
}

// GetInformationAboutChat mocks base method.
func (m *MockChatsUsecase) GetInformationAboutChat(ctx context.Context, userId, chatId uuid.UUID) (*dto.ChatDetailedInformationDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInformationAboutChat", ctx, userId, chatId)
	ret0, _ := ret[0].(*dto.ChatDetailedInformationDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInformationAboutChat indicates an expected call of GetInformationAboutChat.
func (mr *MockChatsUsecaseMockRecorder) GetInformationAboutChat(ctx, userId, chatId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInformationAboutChat", reflect.TypeOf((*MockChatsUsecase)(nil).GetInformationAboutChat), ctx, userId, chatId)
}

// GetUsersDialog mocks base method.
func (m *MockChatsUsecase) GetUsersDialog(ctx context.Context, user1ID, user2ID uuid.UUID) (*dto0.IdDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersDialog", ctx, user1ID, user2ID)
	ret0, _ := ret[0].(*dto0.IdDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersDialog indicates an expected call of GetUsersDialog.
func (mr *MockChatsUsecaseMockRecorder) GetUsersDialog(ctx, user1ID, user2ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersDialog", reflect.TypeOf((*MockChatsUsecase)(nil).GetUsersDialog), ctx, user1ID, user2ID)
}

// SearchChats mocks base method.
func (m *MockChatsUsecase) SearchChats(ctx context.Context, userID uuid.UUID, name string) ([]dto.ChatViewInformationDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchChats", ctx, userID, name)
	ret0, _ := ret[0].([]dto.ChatViewInformationDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchChats indicates an expected call of SearchChats.
func (mr *MockChatsUsecaseMockRecorder) SearchChats(ctx, userID, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchChats", reflect.TypeOf((*MockChatsUsecase)(nil).SearchChats), ctx, userID, name)
}

// UpdateChat mocks base method.
func (m *MockChatsUsecase) UpdateChat(ctx context.Context, userId, chatId uuid.UUID, name, description string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateChat", ctx, userId, chatId, name, description)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateChat indicates an expected call of UpdateChat.
func (mr *MockChatsUsecaseMockRecorder) UpdateChat(ctx, userId, chatId, name, description interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateChat", reflect.TypeOf((*MockChatsUsecase)(nil).UpdateChat), ctx, userId, chatId, name, description)
}

// UploadChatAvatar mocks base method.
func (m *MockChatsUsecase) UploadChatAvatar(ctx context.Context, userID, chatID uuid.UUID, fileData minio.FileData) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadChatAvatar", ctx, userID, chatID, fileData)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadChatAvatar indicates an expected call of UploadChatAvatar.
func (mr *MockChatsUsecaseMockRecorder) UploadChatAvatar(ctx, userID, chatID, fileData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadChatAvatar", reflect.TypeOf((*MockChatsUsecase)(nil).UploadChatAvatar), ctx, userID, chatID, fileData)
}
