// Code generated by MockGen. DO NOT EDIT.
// Source: ../interface/message/message.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/go-park-mail-ru/2025_2_Undefined/internal/transport/dto/chats"
	dto0 "github.com/go-park-mail-ru/2025_2_Undefined/internal/transport/dto/message"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockMessageUsecase is a mock of MessageUsecase interface.
type MockMessageUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockMessageUsecaseMockRecorder
}

// MockMessageUsecaseMockRecorder is the mock recorder for MockMessageUsecase.
type MockMessageUsecaseMockRecorder struct {
	mock *MockMessageUsecase
}

// NewMockMessageUsecase creates a new mock instance.
func NewMockMessageUsecase(ctrl *gomock.Controller) *MockMessageUsecase {
	mock := &MockMessageUsecase{ctrl: ctrl}
	mock.recorder = &MockMessageUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageUsecase) EXPECT() *MockMessageUsecaseMockRecorder {
	return m.recorder
}

// AddMessage mocks base method.
func (m *MockMessageUsecase) AddMessage(ctx context.Context, msg dto0.CreateMessageDTO, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMessage", ctx, msg, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMessage indicates an expected call of AddMessage.
func (mr *MockMessageUsecaseMockRecorder) AddMessage(ctx, msg, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMessage", reflect.TypeOf((*MockMessageUsecase)(nil).AddMessage), ctx, msg, userID)
}

// SubscribeConnectionToChats mocks base method.
func (m *MockMessageUsecase) SubscribeConnectionToChats(ctx context.Context, connectionID, userID uuid.UUID, chatsDTO []dto.ChatViewInformationDTO) <-chan dto0.WebSocketMessageDTO {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeConnectionToChats", ctx, connectionID, userID, chatsDTO)
	ret0, _ := ret[0].(<-chan dto0.WebSocketMessageDTO)
	return ret0
}

// SubscribeConnectionToChats indicates an expected call of SubscribeConnectionToChats.
func (mr *MockMessageUsecaseMockRecorder) SubscribeConnectionToChats(ctx, connectionID, userID, chatsDTO interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeConnectionToChats", reflect.TypeOf((*MockMessageUsecase)(nil).SubscribeConnectionToChats), ctx, connectionID, userID, chatsDTO)
}

// SubscribeUsersOnChat mocks base method.
func (m *MockMessageUsecase) SubscribeUsersOnChat(ctx context.Context, chatID uuid.UUID, members []dto.AddChatMemberDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeUsersOnChat", ctx, chatID, members)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubscribeUsersOnChat indicates an expected call of SubscribeUsersOnChat.
func (mr *MockMessageUsecaseMockRecorder) SubscribeUsersOnChat(ctx, chatID, members interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeUsersOnChat", reflect.TypeOf((*MockMessageUsecase)(nil).SubscribeUsersOnChat), ctx, chatID, members)
}
