// Code generated by MockGen. DO NOT EDIT.
// Source: ../interface/session/session.go

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	dto "github.com/go-park-mail-ru/2025_2_Undefined/internal/transport/dto/session"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockSessionUsecase is a mock of SessionUsecase interface.
type MockSessionUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockSessionUsecaseMockRecorder
}

// MockSessionUsecaseMockRecorder is the mock recorder for MockSessionUsecase.
type MockSessionUsecaseMockRecorder struct {
	mock *MockSessionUsecase
}

// NewMockSessionUsecase creates a new mock instance.
func NewMockSessionUsecase(ctrl *gomock.Controller) *MockSessionUsecase {
	mock := &MockSessionUsecase{ctrl: ctrl}
	mock.recorder = &MockSessionUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionUsecase) EXPECT() *MockSessionUsecaseMockRecorder {
	return m.recorder
}

// GetSessionsByUserID mocks base method.
func (m *MockSessionUsecase) GetSessionsByUserID(userID uuid.UUID) ([]*dto.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionsByUserID", userID)
	ret0, _ := ret[0].([]*dto.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionsByUserID indicates an expected call of GetSessionsByUserID.
func (mr *MockSessionUsecaseMockRecorder) GetSessionsByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionsByUserID", reflect.TypeOf((*MockSessionUsecase)(nil).GetSessionsByUserID), userID)
}

// GetUserIDFromSession mocks base method.
func (m *MockSessionUsecase) GetUserIDFromSession(r *http.Request) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDFromSession", r)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIDFromSession indicates an expected call of GetUserIDFromSession.
func (mr *MockSessionUsecaseMockRecorder) GetUserIDFromSession(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDFromSession", reflect.TypeOf((*MockSessionUsecase)(nil).GetUserIDFromSession), r)
}
