// Code generated by MockGen. DO NOT EDIT.
// Source: ../interface/session/session.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	reflect "reflect"

	dto "github.com/go-park-mail-ru/2025_2_Undefined/internal/transport/dto/session"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockSessionUsecase is a mock of SessionUsecase interface.
type MockSessionUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockSessionUsecaseMockRecorder
}

// MockSessionUsecaseMockRecorder is the mock recorder for MockSessionUsecase.
type MockSessionUsecaseMockRecorder struct {
	mock *MockSessionUsecase
}

// NewMockSessionUsecase creates a new mock instance.
func NewMockSessionUsecase(ctrl *gomock.Controller) *MockSessionUsecase {
	mock := &MockSessionUsecase{ctrl: ctrl}
	mock.recorder = &MockSessionUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionUsecase) EXPECT() *MockSessionUsecaseMockRecorder {
	return m.recorder
}

// DeleteAllSessionWithoutCurrent mocks base method.
func (m *MockSessionUsecase) DeleteAllSessionWithoutCurrent(ctx context.Context, userID, currentSessionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllSessionWithoutCurrent", ctx, userID, currentSessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllSessionWithoutCurrent indicates an expected call of DeleteAllSessionWithoutCurrent.
func (mr *MockSessionUsecaseMockRecorder) DeleteAllSessionWithoutCurrent(ctx, userID, currentSessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllSessionWithoutCurrent", reflect.TypeOf((*MockSessionUsecase)(nil).DeleteAllSessionWithoutCurrent), ctx, userID, currentSessionID)
}

// DeleteSession mocks base method.
func (m *MockSessionUsecase) DeleteSession(ctx context.Context, userID, sessionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, userID, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockSessionUsecaseMockRecorder) DeleteSession(ctx, userID, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockSessionUsecase)(nil).DeleteSession), ctx, userID, sessionID)
}

// GetSession mocks base method.
func (m *MockSessionUsecase) GetSession(ctx context.Context, sessionID uuid.UUID) (*dto.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, sessionID)
	ret0, _ := ret[0].(*dto.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockSessionUsecaseMockRecorder) GetSession(ctx, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockSessionUsecase)(nil).GetSession), ctx, sessionID)
}

// GetSessionsByUserID mocks base method.
func (m *MockSessionUsecase) GetSessionsByUserID(ctx context.Context, userID uuid.UUID) ([]*dto.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionsByUserID", ctx, userID)
	ret0, _ := ret[0].([]*dto.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionsByUserID indicates an expected call of GetSessionsByUserID.
func (mr *MockSessionUsecaseMockRecorder) GetSessionsByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionsByUserID", reflect.TypeOf((*MockSessionUsecase)(nil).GetSessionsByUserID), ctx, userID)
}

// UpdateSession mocks base method.
func (m *MockSessionUsecase) UpdateSession(ctx context.Context, sessionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSession indicates an expected call of UpdateSession.
func (mr *MockSessionUsecaseMockRecorder) UpdateSession(ctx, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSession", reflect.TypeOf((*MockSessionUsecase)(nil).UpdateSession), ctx, sessionID)
}

// MockSessionUtils is a mock of SessionUtils interface.
type MockSessionUtils struct {
	ctrl     *gomock.Controller
	recorder *MockSessionUtilsMockRecorder
}

// MockSessionUtilsMockRecorder is the mock recorder for MockSessionUtils.
type MockSessionUtilsMockRecorder struct {
	mock *MockSessionUtils
}

// NewMockSessionUtils creates a new mock instance.
func NewMockSessionUtils(ctrl *gomock.Controller) *MockSessionUtils {
	mock := &MockSessionUtils{ctrl: ctrl}
	mock.recorder = &MockSessionUtilsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionUtils) EXPECT() *MockSessionUtilsMockRecorder {
	return m.recorder
}

// GetSessionFromCookie mocks base method.
func (m *MockSessionUtils) GetSessionFromCookie(r *http.Request) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionFromCookie", r)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionFromCookie indicates an expected call of GetSessionFromCookie.
func (mr *MockSessionUtilsMockRecorder) GetSessionFromCookie(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionFromCookie", reflect.TypeOf((*MockSessionUtils)(nil).GetSessionFromCookie), r)
}

// GetSessionsByUserID mocks base method.
func (m *MockSessionUtils) GetSessionsByUserID(userID uuid.UUID) ([]*dto.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionsByUserID", userID)
	ret0, _ := ret[0].([]*dto.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionsByUserID indicates an expected call of GetSessionsByUserID.
func (mr *MockSessionUtilsMockRecorder) GetSessionsByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionsByUserID", reflect.TypeOf((*MockSessionUtils)(nil).GetSessionsByUserID), userID)
}

// GetUserIDFromSession mocks base method.
func (m *MockSessionUtils) GetUserIDFromSession(r *http.Request) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDFromSession", r)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIDFromSession indicates an expected call of GetUserIDFromSession.
func (mr *MockSessionUtilsMockRecorder) GetUserIDFromSession(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDFromSession", reflect.TypeOf((*MockSessionUtils)(nil).GetUserIDFromSession), r)
}
