// Code generated by MockGen. DO NOT EDIT.
// Source: ../interface/chats/chats.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/go-park-mail-ru/2025_2_Undefined/internal/transport/dto/chats"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockChatsUsecase is a mock of ChatsUsecase interface.
type MockChatsUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockChatsUsecaseMockRecorder
}

// MockChatsUsecaseMockRecorder is the mock recorder for MockChatsUsecase.
type MockChatsUsecaseMockRecorder struct {
	mock *MockChatsUsecase
}

// NewMockChatsUsecase creates a new mock instance.
func NewMockChatsUsecase(ctrl *gomock.Controller) *MockChatsUsecase {
	mock := &MockChatsUsecase{ctrl: ctrl}
	mock.recorder = &MockChatsUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatsUsecase) EXPECT() *MockChatsUsecaseMockRecorder {
	return m.recorder
}

// AddUsersToChat mocks base method.
func (m *MockChatsUsecase) AddUsersToChat(ctx context.Context, chatID uuid.UUID, users []dto.AddChatMemberDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUsersToChat", ctx, chatID, users)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUsersToChat indicates an expected call of AddUsersToChat.
func (mr *MockChatsUsecaseMockRecorder) AddUsersToChat(ctx, chatID, users interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUsersToChat", reflect.TypeOf((*MockChatsUsecase)(nil).AddUsersToChat), ctx, chatID, users)
}

// CreateChat mocks base method.
func (m *MockChatsUsecase) CreateChat(ctx context.Context, chatDTO dto.ChatCreateInformationDTO) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChat", ctx, chatDTO)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChat indicates an expected call of CreateChat.
func (mr *MockChatsUsecaseMockRecorder) CreateChat(ctx, chatDTO interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChat", reflect.TypeOf((*MockChatsUsecase)(nil).CreateChat), ctx, chatDTO)
}

// GetChats mocks base method.
func (m *MockChatsUsecase) GetChats(ctx context.Context, userId uuid.UUID) ([]dto.ChatViewInformationDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChats", ctx, userId)
	ret0, _ := ret[0].([]dto.ChatViewInformationDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChats indicates an expected call of GetChats.
func (mr *MockChatsUsecaseMockRecorder) GetChats(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChats", reflect.TypeOf((*MockChatsUsecase)(nil).GetChats), ctx, userId)
}

// GetInformationAboutChat mocks base method.
func (m *MockChatsUsecase) GetInformationAboutChat(ctx context.Context, userId, chatId uuid.UUID) (*dto.ChatDetailedInformationDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInformationAboutChat", ctx, userId, chatId)
	ret0, _ := ret[0].(*dto.ChatDetailedInformationDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInformationAboutChat indicates an expected call of GetInformationAboutChat.
func (mr *MockChatsUsecaseMockRecorder) GetInformationAboutChat(ctx, userId, chatId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInformationAboutChat", reflect.TypeOf((*MockChatsUsecase)(nil).GetInformationAboutChat), ctx, userId, chatId)
}
