// Code generated by MockGen. DO NOT EDIT.
// Source: ../interface/contact/contact.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2025_2_Undefined/internal/models/contact"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockContactRepository is a mock of ContactRepository interface.
type MockContactRepository struct {
	ctrl     *gomock.Controller
	recorder *MockContactRepositoryMockRecorder
}

// MockContactRepositoryMockRecorder is the mock recorder for MockContactRepository.
type MockContactRepositoryMockRecorder struct {
	mock *MockContactRepository
}

// NewMockContactRepository creates a new mock instance.
func NewMockContactRepository(ctrl *gomock.Controller) *MockContactRepository {
	mock := &MockContactRepository{ctrl: ctrl}
	mock.recorder = &MockContactRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContactRepository) EXPECT() *MockContactRepositoryMockRecorder {
	return m.recorder
}

// CreateContact mocks base method.
func (m *MockContactRepository) CreateContact(ctx context.Context, user_id, contact_user_id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateContact", ctx, user_id, contact_user_id)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateContact indicates an expected call of CreateContact.
func (mr *MockContactRepositoryMockRecorder) CreateContact(ctx, user_id, contact_user_id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateContact", reflect.TypeOf((*MockContactRepository)(nil).CreateContact), ctx, user_id, contact_user_id)
}

// GetContactsByUserID mocks base method.
func (m *MockContactRepository) GetContactsByUserID(ctx context.Context, user_id uuid.UUID) ([]*models.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContactsByUserID", ctx, user_id)
	ret0, _ := ret[0].([]*models.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContactsByUserID indicates an expected call of GetContactsByUserID.
func (mr *MockContactRepositoryMockRecorder) GetContactsByUserID(ctx, user_id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContactsByUserID", reflect.TypeOf((*MockContactRepository)(nil).GetContactsByUserID), ctx, user_id)
}
