// Code generated by MockGen. DO NOT EDIT.
// Source: session_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/go-park-mail-ru/2025_2_Undefined/internal/transport/dto/session"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockISessionUsecase is a mock of ISessionUsecase interface.
type MockISessionUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockISessionUsecaseMockRecorder
}

// MockISessionUsecaseMockRecorder is the mock recorder for MockISessionUsecase.
type MockISessionUsecaseMockRecorder struct {
	mock *MockISessionUsecase
}

// NewMockISessionUsecase creates a new mock instance.
func NewMockISessionUsecase(ctrl *gomock.Controller) *MockISessionUsecase {
	mock := &MockISessionUsecase{ctrl: ctrl}
	mock.recorder = &MockISessionUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISessionUsecase) EXPECT() *MockISessionUsecaseMockRecorder {
	return m.recorder
}

// DeleteAllSessionWithoutCurrent mocks base method.
func (m *MockISessionUsecase) DeleteAllSessionWithoutCurrent(ctx context.Context, userID, currentSessionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllSessionWithoutCurrent", ctx, userID, currentSessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllSessionWithoutCurrent indicates an expected call of DeleteAllSessionWithoutCurrent.
func (mr *MockISessionUsecaseMockRecorder) DeleteAllSessionWithoutCurrent(ctx, userID, currentSessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllSessionWithoutCurrent", reflect.TypeOf((*MockISessionUsecase)(nil).DeleteAllSessionWithoutCurrent), ctx, userID, currentSessionID)
}

// DeleteSession mocks base method.
func (m *MockISessionUsecase) DeleteSession(ctx context.Context, userID, sessionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, userID, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockISessionUsecaseMockRecorder) DeleteSession(ctx, userID, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockISessionUsecase)(nil).DeleteSession), ctx, userID, sessionID)
}

// GetSession mocks base method.
func (m *MockISessionUsecase) GetSession(ctx context.Context, sessionID uuid.UUID) (*dto.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, sessionID)
	ret0, _ := ret[0].(*dto.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockISessionUsecaseMockRecorder) GetSession(ctx, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockISessionUsecase)(nil).GetSession), ctx, sessionID)
}

// GetSessionsByUserID mocks base method.
func (m *MockISessionUsecase) GetSessionsByUserID(ctx context.Context, userID uuid.UUID) ([]*dto.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionsByUserID", ctx, userID)
	ret0, _ := ret[0].([]*dto.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionsByUserID indicates an expected call of GetSessionsByUserID.
func (mr *MockISessionUsecaseMockRecorder) GetSessionsByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionsByUserID", reflect.TypeOf((*MockISessionUsecase)(nil).GetSessionsByUserID), ctx, userID)
}

// UpdateSession mocks base method.
func (m *MockISessionUsecase) UpdateSession(ctx context.Context, sessionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSession indicates an expected call of UpdateSession.
func (mr *MockISessionUsecaseMockRecorder) UpdateSession(ctx, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSession", reflect.TypeOf((*MockISessionUsecase)(nil).UpdateSession), ctx, sessionID)
}
