// Code generated by MockGen. DO NOT EDIT.
// Source: contact_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/go-park-mail-ru/2025_2_Undefined/internal/transport/dto/contact"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockIContactUsecase is a mock of IContactUsecase interface.
type MockIContactUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockIContactUsecaseMockRecorder
}

// MockIContactUsecaseMockRecorder is the mock recorder for MockIContactUsecase.
type MockIContactUsecaseMockRecorder struct {
	mock *MockIContactUsecase
}

// NewMockIContactUsecase creates a new mock instance.
func NewMockIContactUsecase(ctrl *gomock.Controller) *MockIContactUsecase {
	mock := &MockIContactUsecase{ctrl: ctrl}
	mock.recorder = &MockIContactUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIContactUsecase) EXPECT() *MockIContactUsecaseMockRecorder {
	return m.recorder
}

// CreateContact mocks base method.
func (m *MockIContactUsecase) CreateContact(ctx context.Context, req *dto.PostContactDTO, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateContact", ctx, req, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateContact indicates an expected call of CreateContact.
func (mr *MockIContactUsecaseMockRecorder) CreateContact(ctx, req, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateContact", reflect.TypeOf((*MockIContactUsecase)(nil).CreateContact), ctx, req, userID)
}

// GetContacts mocks base method.
func (m *MockIContactUsecase) GetContacts(ctx context.Context, userID uuid.UUID) ([]*dto.GetContactsDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContacts", ctx, userID)
	ret0, _ := ret[0].([]*dto.GetContactsDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContacts indicates an expected call of GetContacts.
func (mr *MockIContactUsecaseMockRecorder) GetContacts(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContacts", reflect.TypeOf((*MockIContactUsecase)(nil).GetContacts), ctx, userID)
}

// ReindexAllContacts mocks base method.
func (m *MockIContactUsecase) ReindexAllContacts(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReindexAllContacts", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReindexAllContacts indicates an expected call of ReindexAllContacts.
func (mr *MockIContactUsecaseMockRecorder) ReindexAllContacts(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReindexAllContacts", reflect.TypeOf((*MockIContactUsecase)(nil).ReindexAllContacts), ctx)
}

// SearchContacts mocks base method.
func (m *MockIContactUsecase) SearchContacts(ctx context.Context, userID uuid.UUID, query string) ([]*dto.GetContactsDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchContacts", ctx, userID, query)
	ret0, _ := ret[0].([]*dto.GetContactsDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchContacts indicates an expected call of SearchContacts.
func (mr *MockIContactUsecaseMockRecorder) SearchContacts(ctx, userID, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchContacts", reflect.TypeOf((*MockIContactUsecase)(nil).SearchContacts), ctx, userID, query)
}
