// Code generated by MockGen. DO NOT EDIT.
// Source: ../interface/listener/listener.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	message "github.com/go-park-mail-ru/2025_2_Undefined/internal/transport/dto/message"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockListenerMapInterface is a mock of ListenerMapInterface interface.
type MockListenerMapInterface struct {
	ctrl     *gomock.Controller
	recorder *MockListenerMapInterfaceMockRecorder
}

// MockListenerMapInterfaceMockRecorder is the mock recorder for MockListenerMapInterface.
type MockListenerMapInterfaceMockRecorder struct {
	mock *MockListenerMapInterface
}

// NewMockListenerMapInterface creates a new mock instance.
func NewMockListenerMapInterface(ctrl *gomock.Controller) *MockListenerMapInterface {
	mock := &MockListenerMapInterface{ctrl: ctrl}
	mock.recorder = &MockListenerMapInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListenerMapInterface) EXPECT() *MockListenerMapInterfaceMockRecorder {
	return m.recorder
}

// CleanInactiveChats mocks base method.
func (m *MockListenerMapInterface) CleanInactiveChats() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanInactiveChats")
	ret0, _ := ret[0].(int)
	return ret0
}

// CleanInactiveChats indicates an expected call of CleanInactiveChats.
func (mr *MockListenerMapInterfaceMockRecorder) CleanInactiveChats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanInactiveChats", reflect.TypeOf((*MockListenerMapInterface)(nil).CleanInactiveChats))
}

// CleanInactiveReaders mocks base method.
func (m *MockListenerMapInterface) CleanInactiveReaders() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanInactiveReaders")
	ret0, _ := ret[0].(int)
	return ret0
}

// CleanInactiveReaders indicates an expected call of CleanInactiveReaders.
func (mr *MockListenerMapInterfaceMockRecorder) CleanInactiveReaders() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanInactiveReaders", reflect.TypeOf((*MockListenerMapInterface)(nil).CleanInactiveReaders))
}

// CloseAll mocks base method.
func (m *MockListenerMapInterface) CloseAll() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CloseAll")
}

// CloseAll indicates an expected call of CloseAll.
func (mr *MockListenerMapInterfaceMockRecorder) CloseAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseAll", reflect.TypeOf((*MockListenerMapInterface)(nil).CloseAll))
}

// GetChatListeners mocks base method.
func (m *MockListenerMapInterface) GetChatListeners(chatId uuid.UUID) map[uuid.UUID]chan message.MessageDTO {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatListeners", chatId)
	ret0, _ := ret[0].(map[uuid.UUID]chan message.MessageDTO)
	return ret0
}

// GetChatListeners indicates an expected call of GetChatListeners.
func (mr *MockListenerMapInterfaceMockRecorder) GetChatListeners(chatId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatListeners", reflect.TypeOf((*MockListenerMapInterface)(nil).GetChatListeners), chatId)
}

// SubscribeConnectionToChat mocks base method.
func (m *MockListenerMapInterface) SubscribeConnectionToChat(userId, chatId uuid.UUID) <-chan message.MessageDTO {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeConnectionToChat", userId, chatId)
	ret0, _ := ret[0].(<-chan message.MessageDTO)
	return ret0
}

// SubscribeConnectionToChat indicates an expected call of SubscribeConnectionToChat.
func (mr *MockListenerMapInterfaceMockRecorder) SubscribeConnectionToChat(userId, chatId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeConnectionToChat", reflect.TypeOf((*MockListenerMapInterface)(nil).SubscribeConnectionToChat), userId, chatId)
}
