// Code generated by MockGen. DO NOT EDIT.
// Source: auth_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/go-park-mail-ru/2025_2_Undefined/internal/transport/dto/auth"
	dto0 "github.com/go-park-mail-ru/2025_2_Undefined/internal/transport/dto/utils"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockIAuthUsecase is a mock of IAuthUsecase interface.
type MockIAuthUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockIAuthUsecaseMockRecorder
}

// MockIAuthUsecaseMockRecorder is the mock recorder for MockIAuthUsecase.
type MockIAuthUsecaseMockRecorder struct {
	mock *MockIAuthUsecase
}

// NewMockIAuthUsecase creates a new mock instance.
func NewMockIAuthUsecase(ctrl *gomock.Controller) *MockIAuthUsecase {
	mock := &MockIAuthUsecase{ctrl: ctrl}
	mock.recorder = &MockIAuthUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAuthUsecase) EXPECT() *MockIAuthUsecaseMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockIAuthUsecase) Login(ctx context.Context, req *dto.LoginRequest, device string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, req, device)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockIAuthUsecaseMockRecorder) Login(ctx, req, device interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockIAuthUsecase)(nil).Login), ctx, req, device)
}

// Logout mocks base method.
func (m *MockIAuthUsecase) Logout(ctx context.Context, SessionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, SessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockIAuthUsecaseMockRecorder) Logout(ctx, SessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockIAuthUsecase)(nil).Logout), ctx, SessionID)
}

// Register mocks base method.
func (m *MockIAuthUsecase) Register(ctx context.Context, req *dto.RegisterRequest, device string) (uuid.UUID, *dto0.ValidationErrorsDTO) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, req, device)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(*dto0.ValidationErrorsDTO)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockIAuthUsecaseMockRecorder) Register(ctx, req, device interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockIAuthUsecase)(nil).Register), ctx, req, device)
}
