// Code generated by MockGen. DO NOT EDIT.
// Source: ../interface/chats/chats.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2025_2_Undefined/internal/models/chats"
	models0 "github.com/go-park-mail-ru/2025_2_Undefined/internal/models/message"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockChatsRepository is a mock of ChatsRepository interface.
type MockChatsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockChatsRepositoryMockRecorder
}

// MockChatsRepositoryMockRecorder is the mock recorder for MockChatsRepository.
type MockChatsRepositoryMockRecorder struct {
	mock *MockChatsRepository
}

// NewMockChatsRepository creates a new mock instance.
func NewMockChatsRepository(ctrl *gomock.Controller) *MockChatsRepository {
	mock := &MockChatsRepository{ctrl: ctrl}
	mock.recorder = &MockChatsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatsRepository) EXPECT() *MockChatsRepositoryMockRecorder {
	return m.recorder
}

// CreateChat mocks base method.
func (m *MockChatsRepository) CreateChat(ctx context.Context, chat models.Chat, usersInfo []models.UserInfo, usersNames []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChat", ctx, chat, usersInfo, usersNames)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateChat indicates an expected call of CreateChat.
func (mr *MockChatsRepositoryMockRecorder) CreateChat(ctx, chat, usersInfo, usersNames interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChat", reflect.TypeOf((*MockChatsRepository)(nil).CreateChat), ctx, chat, usersInfo, usersNames)
}

// GetChat mocks base method.
func (m *MockChatsRepository) GetChat(ctx context.Context, userId, chatId uuid.UUID) (*models.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChat", ctx, userId, chatId)
	ret0, _ := ret[0].(*models.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChat indicates an expected call of GetChat.
func (mr *MockChatsRepositoryMockRecorder) GetChat(ctx, userId, chatId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChat", reflect.TypeOf((*MockChatsRepository)(nil).GetChat), ctx, userId, chatId)
}

// GetChats mocks base method.
func (m *MockChatsRepository) GetChats(ctx context.Context, userId uuid.UUID) ([]models.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChats", ctx, userId)
	ret0, _ := ret[0].([]models.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChats indicates an expected call of GetChats.
func (mr *MockChatsRepositoryMockRecorder) GetChats(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChats", reflect.TypeOf((*MockChatsRepository)(nil).GetChats), ctx, userId)
}

// GetLastMessagesOfChats mocks base method.
func (m *MockChatsRepository) GetLastMessagesOfChats(ctx context.Context, userId uuid.UUID) ([]models0.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastMessagesOfChats", ctx, userId)
	ret0, _ := ret[0].([]models0.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastMessagesOfChats indicates an expected call of GetLastMessagesOfChats.
func (mr *MockChatsRepositoryMockRecorder) GetLastMessagesOfChats(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastMessagesOfChats", reflect.TypeOf((*MockChatsRepository)(nil).GetLastMessagesOfChats), ctx, userId)
}

// GetMessagesOfChat mocks base method.
func (m *MockChatsRepository) GetMessagesOfChat(ctx context.Context, chatId uuid.UUID, offset, limit int) ([]models0.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesOfChat", ctx, chatId, offset, limit)
	ret0, _ := ret[0].([]models0.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesOfChat indicates an expected call of GetMessagesOfChat.
func (mr *MockChatsRepositoryMockRecorder) GetMessagesOfChat(ctx, chatId, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesOfChat", reflect.TypeOf((*MockChatsRepository)(nil).GetMessagesOfChat), ctx, chatId, offset, limit)
}

// GetUserInfo mocks base method.
func (m *MockChatsRepository) GetUserInfo(ctx context.Context, userId, chatId uuid.UUID) (*models.UserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfo", ctx, userId, chatId)
	ret0, _ := ret[0].(*models.UserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfo indicates an expected call of GetUserInfo.
func (mr *MockChatsRepositoryMockRecorder) GetUserInfo(ctx, userId, chatId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfo", reflect.TypeOf((*MockChatsRepository)(nil).GetUserInfo), ctx, userId, chatId)
}

// GetUsersOfChat mocks base method.
func (m *MockChatsRepository) GetUsersOfChat(ctx context.Context, chatId uuid.UUID) ([]models.UserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersOfChat", ctx, chatId)
	ret0, _ := ret[0].([]models.UserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersOfChat indicates an expected call of GetUsersOfChat.
func (mr *MockChatsRepositoryMockRecorder) GetUsersOfChat(ctx, chatId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersOfChat", reflect.TypeOf((*MockChatsRepository)(nil).GetUsersOfChat), ctx, chatId)
}

// InsertUsersToChat mocks base method.
func (m *MockChatsRepository) InsertUsersToChat(ctx context.Context, chatID uuid.UUID, usersInfo []models.UserInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertUsersToChat", ctx, chatID, usersInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertUsersToChat indicates an expected call of InsertUsersToChat.
func (mr *MockChatsRepositoryMockRecorder) InsertUsersToChat(ctx, chatID, usersInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertUsersToChat", reflect.TypeOf((*MockChatsRepository)(nil).InsertUsersToChat), ctx, chatID, usersInfo)
}
