// Code generated by MockGen. DO NOT EDIT.
// Source: ../interface/chats/chats.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2025_2_Undefined/internal/models/chats"
	models0 "github.com/go-park-mail-ru/2025_2_Undefined/internal/models/message"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockChatsRepository is a mock of ChatsRepository interface.
type MockChatsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockChatsRepositoryMockRecorder
}

// MockChatsRepositoryMockRecorder is the mock recorder for MockChatsRepository.
type MockChatsRepositoryMockRecorder struct {
	mock *MockChatsRepository
}

// NewMockChatsRepository creates a new mock instance.
func NewMockChatsRepository(ctrl *gomock.Controller) *MockChatsRepository {
	mock := &MockChatsRepository{ctrl: ctrl}
	mock.recorder = &MockChatsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatsRepository) EXPECT() *MockChatsRepositoryMockRecorder {
	return m.recorder
}

// CheckUserHasRole mocks base method.
func (m *MockChatsRepository) CheckUserHasRole(ctx context.Context, userID, chatID uuid.UUID, role string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserHasRole", ctx, userID, chatID, role)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserHasRole indicates an expected call of CheckUserHasRole.
func (mr *MockChatsRepositoryMockRecorder) CheckUserHasRole(ctx, userID, chatID, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserHasRole", reflect.TypeOf((*MockChatsRepository)(nil).CheckUserHasRole), ctx, userID, chatID, role)
}

// CreateChat mocks base method.
func (m *MockChatsRepository) CreateChat(ctx context.Context, chat models.Chat, usersInfo []models.UserInfo, usersNames []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChat", ctx, chat, usersInfo, usersNames)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateChat indicates an expected call of CreateChat.
func (mr *MockChatsRepositoryMockRecorder) CreateChat(ctx, chat, usersInfo, usersNames interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChat", reflect.TypeOf((*MockChatsRepository)(nil).CreateChat), ctx, chat, usersInfo, usersNames)
}

// DeleteChat mocks base method.
func (m *MockChatsRepository) DeleteChat(ctx context.Context, userID, chatID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChat", ctx, userID, chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChat indicates an expected call of DeleteChat.
func (mr *MockChatsRepositoryMockRecorder) DeleteChat(ctx, userID, chatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChat", reflect.TypeOf((*MockChatsRepository)(nil).DeleteChat), ctx, userID, chatID)
}

// GetChat mocks base method.
func (m *MockChatsRepository) GetChat(ctx context.Context, chatID uuid.UUID) (*models.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChat", ctx, chatID)
	ret0, _ := ret[0].(*models.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChat indicates an expected call of GetChat.
func (mr *MockChatsRepositoryMockRecorder) GetChat(ctx, chatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChat", reflect.TypeOf((*MockChatsRepository)(nil).GetChat), ctx, chatID)
}

// GetChats mocks base method.
func (m *MockChatsRepository) GetChats(ctx context.Context, userID uuid.UUID) ([]models.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChats", ctx, userID)
	ret0, _ := ret[0].([]models.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChats indicates an expected call of GetChats.
func (mr *MockChatsRepositoryMockRecorder) GetChats(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChats", reflect.TypeOf((*MockChatsRepository)(nil).GetChats), ctx, userID)
}

// GetLastMessagesOfChats mocks base method.
func (m *MockChatsRepository) GetLastMessagesOfChats(ctx context.Context, userID uuid.UUID) ([]models0.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastMessagesOfChats", ctx, userID)
	ret0, _ := ret[0].([]models0.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastMessagesOfChats indicates an expected call of GetLastMessagesOfChats.
func (mr *MockChatsRepositoryMockRecorder) GetLastMessagesOfChats(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastMessagesOfChats", reflect.TypeOf((*MockChatsRepository)(nil).GetLastMessagesOfChats), ctx, userID)
}

// GetMessagesOfChat mocks base method.
func (m *MockChatsRepository) GetMessagesOfChat(ctx context.Context, chatID uuid.UUID, offset, limit int) ([]models0.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesOfChat", ctx, chatID, offset, limit)
	ret0, _ := ret[0].([]models0.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesOfChat indicates an expected call of GetMessagesOfChat.
func (mr *MockChatsRepositoryMockRecorder) GetMessagesOfChat(ctx, chatID, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesOfChat", reflect.TypeOf((*MockChatsRepository)(nil).GetMessagesOfChat), ctx, chatID, offset, limit)
}

// GetUserInfo mocks base method.
func (m *MockChatsRepository) GetUserInfo(ctx context.Context, userID, chatID uuid.UUID) (*models.UserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfo", ctx, userID, chatID)
	ret0, _ := ret[0].(*models.UserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfo indicates an expected call of GetUserInfo.
func (mr *MockChatsRepositoryMockRecorder) GetUserInfo(ctx, userID, chatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfo", reflect.TypeOf((*MockChatsRepository)(nil).GetUserInfo), ctx, userID, chatID)
}

// GetUsersDialog mocks base method.
func (m *MockChatsRepository) GetUsersDialog(ctx context.Context, user1ID, user2ID uuid.UUID) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersDialog", ctx, user1ID, user2ID)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersDialog indicates an expected call of GetUsersDialog.
func (mr *MockChatsRepositoryMockRecorder) GetUsersDialog(ctx, user1ID, user2ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersDialog", reflect.TypeOf((*MockChatsRepository)(nil).GetUsersDialog), ctx, user1ID, user2ID)
}

// GetUsersOfChat mocks base method.
func (m *MockChatsRepository) GetUsersOfChat(ctx context.Context, chatID uuid.UUID) ([]models.UserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersOfChat", ctx, chatID)
	ret0, _ := ret[0].([]models.UserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersOfChat indicates an expected call of GetUsersOfChat.
func (mr *MockChatsRepositoryMockRecorder) GetUsersOfChat(ctx, chatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersOfChat", reflect.TypeOf((*MockChatsRepository)(nil).GetUsersOfChat), ctx, chatID)
}

// InsertUsersToChat mocks base method.
func (m *MockChatsRepository) InsertUsersToChat(ctx context.Context, chatID uuid.UUID, usersInfo []models.UserInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertUsersToChat", ctx, chatID, usersInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertUsersToChat indicates an expected call of InsertUsersToChat.
func (mr *MockChatsRepositoryMockRecorder) InsertUsersToChat(ctx, chatID, usersInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertUsersToChat", reflect.TypeOf((*MockChatsRepository)(nil).InsertUsersToChat), ctx, chatID, usersInfo)
}

// UpdateChat mocks base method.
func (m *MockChatsRepository) UpdateChat(ctx context.Context, userID, chatID uuid.UUID, name, description string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateChat", ctx, userID, chatID, name, description)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateChat indicates an expected call of UpdateChat.
func (mr *MockChatsRepositoryMockRecorder) UpdateChat(ctx, userID, chatID, name, description interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateChat", reflect.TypeOf((*MockChatsRepository)(nil).UpdateChat), ctx, userID, chatID, name, description)
}
