// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2025_2_Undefined/internal/transport/generated/chats (interfaces: ChatServiceClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	chats "github.com/go-park-mail-ru/2025_2_Undefined/internal/transport/generated/chats"
	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockChatServiceClient is a mock of ChatServiceClient interface.
type MockChatServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockChatServiceClientMockRecorder
}

// MockChatServiceClientMockRecorder is the mock recorder for MockChatServiceClient.
type MockChatServiceClientMockRecorder struct {
	mock *MockChatServiceClient
}

// NewMockChatServiceClient creates a new mock instance.
func NewMockChatServiceClient(ctrl *gomock.Controller) *MockChatServiceClient {
	mock := &MockChatServiceClient{ctrl: ctrl}
	mock.recorder = &MockChatServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatServiceClient) EXPECT() *MockChatServiceClientMockRecorder {
	return m.recorder
}

// AddUserToChat mocks base method.
func (m *MockChatServiceClient) AddUserToChat(arg0 context.Context, arg1 *chats.AddUserToChatReq, arg2 ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddUserToChat", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddUserToChat indicates an expected call of AddUserToChat.
func (mr *MockChatServiceClientMockRecorder) AddUserToChat(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserToChat", reflect.TypeOf((*MockChatServiceClient)(nil).AddUserToChat), varargs...)
}

// CreateChat mocks base method.
func (m *MockChatServiceClient) CreateChat(arg0 context.Context, arg1 *chats.CreateChatReq, arg2 ...grpc.CallOption) (*chats.IdRes, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateChat", varargs...)
	ret0, _ := ret[0].(*chats.IdRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChat indicates an expected call of CreateChat.
func (mr *MockChatServiceClientMockRecorder) CreateChat(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChat", reflect.TypeOf((*MockChatServiceClient)(nil).CreateChat), varargs...)
}

// DeleteChat mocks base method.
func (m *MockChatServiceClient) DeleteChat(arg0 context.Context, arg1 *chats.GetChatReq, arg2 ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteChat", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteChat indicates an expected call of DeleteChat.
func (mr *MockChatServiceClientMockRecorder) DeleteChat(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChat", reflect.TypeOf((*MockChatServiceClient)(nil).DeleteChat), varargs...)
}

// GetChat mocks base method.
func (m *MockChatServiceClient) GetChat(arg0 context.Context, arg1 *chats.GetChatReq, arg2 ...grpc.CallOption) (*chats.ChatDetailedInformation, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetChat", varargs...)
	ret0, _ := ret[0].(*chats.ChatDetailedInformation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChat indicates an expected call of GetChat.
func (mr *MockChatServiceClientMockRecorder) GetChat(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChat", reflect.TypeOf((*MockChatServiceClient)(nil).GetChat), varargs...)
}

// GetChatAvatars mocks base method.
func (m *MockChatServiceClient) GetChatAvatars(arg0 context.Context, arg1 *chats.GetChatAvatarsReq, arg2 ...grpc.CallOption) (*chats.GetChatAvatarsRes, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetChatAvatars", varargs...)
	ret0, _ := ret[0].(*chats.GetChatAvatarsRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatAvatars indicates an expected call of GetChatAvatars.
func (mr *MockChatServiceClientMockRecorder) GetChatAvatars(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatAvatars", reflect.TypeOf((*MockChatServiceClient)(nil).GetChatAvatars), varargs...)
}

// GetChats mocks base method.
func (m *MockChatServiceClient) GetChats(arg0 context.Context, arg1 *chats.GetChatsReq, arg2 ...grpc.CallOption) (*chats.GetChatsRes, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetChats", varargs...)
	ret0, _ := ret[0].(*chats.GetChatsRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChats indicates an expected call of GetChats.
func (mr *MockChatServiceClientMockRecorder) GetChats(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChats", reflect.TypeOf((*MockChatServiceClient)(nil).GetChats), varargs...)
}

// GetUsersDialog mocks base method.
func (m *MockChatServiceClient) GetUsersDialog(arg0 context.Context, arg1 *chats.GetUsersDialogReq, arg2 ...grpc.CallOption) (*chats.IdRes, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUsersDialog", varargs...)
	ret0, _ := ret[0].(*chats.IdRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersDialog indicates an expected call of GetUsersDialog.
func (mr *MockChatServiceClientMockRecorder) GetUsersDialog(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersDialog", reflect.TypeOf((*MockChatServiceClient)(nil).GetUsersDialog), varargs...)
}

// RemoveUserFromChat mocks base method.
func (m *MockChatServiceClient) RemoveUserFromChat(arg0 context.Context, arg1 *chats.RemoveUserFromChatReq, arg2 ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveUserFromChat", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveUserFromChat indicates an expected call of RemoveUserFromChat.
func (mr *MockChatServiceClientMockRecorder) RemoveUserFromChat(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserFromChat", reflect.TypeOf((*MockChatServiceClient)(nil).RemoveUserFromChat), varargs...)
}

// UpdateChat mocks base method.
func (m *MockChatServiceClient) UpdateChat(arg0 context.Context, arg1 *chats.UpdateChatReq, arg2 ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateChat", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateChat indicates an expected call of UpdateChat.
func (mr *MockChatServiceClientMockRecorder) UpdateChat(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateChat", reflect.TypeOf((*MockChatServiceClient)(nil).UpdateChat), varargs...)
}

// UploadChatAvatar mocks base method.
func (m *MockChatServiceClient) UploadChatAvatar(arg0 context.Context, arg1 *chats.UploadChatAvatarReq, arg2 ...grpc.CallOption) (*chats.UploadChatAvatarRes, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UploadChatAvatar", varargs...)
	ret0, _ := ret[0].(*chats.UploadChatAvatarRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadChatAvatar indicates an expected call of UploadChatAvatar.
func (mr *MockChatServiceClientMockRecorder) UploadChatAvatar(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadChatAvatar", reflect.TypeOf((*MockChatServiceClient)(nil).UploadChatAvatar), varargs...)
}
