// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2025_2_Undefined/internal/transport/generated/chats (interfaces: MessageServiceClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	"context"
	"reflect"

	chats "github.com/go-park-mail-ru/2025_2_Undefined/internal/transport/generated/chats"
	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockMessageServiceClient is a mock of MessageServiceClient interface.
type MockMessageServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockMessageServiceClientMockRecorder
}

// MockMessageServiceClientMockRecorder is the mock recorder for MockMessageServiceClient.
type MockMessageServiceClientMockRecorder struct {
	mock *MockMessageServiceClient
}

// NewMockMessageServiceClient creates a new mock instance.
func NewMockMessageServiceClient(ctrl *gomock.Controller) *MockMessageServiceClient {
	mock := &MockMessageServiceClient{ctrl: ctrl}
	mock.recorder = &MockMessageServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageServiceClient) EXPECT() *MockMessageServiceClientMockRecorder {
	return m.recorder
}

// HandleSendMessage mocks base method.
func (m *MockMessageServiceClient) HandleSendMessage(arg0 context.Context, arg1 *chats.MessageEventReq, arg2 ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HandleSendMessage", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleSendMessage indicates an expected call of HandleSendMessage.
func (mr *MockMessageServiceClientMockRecorder) HandleSendMessage(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSendMessage", reflect.TypeOf((*MockMessageServiceClient)(nil).HandleSendMessage), varargs...)
}

// StreamMessagesForUser mocks base method.
func (m *MockMessageServiceClient) StreamMessagesForUser(arg0 context.Context, arg1 *chats.StreamMessagesForUserReq, arg2 ...grpc.CallOption) (grpc.ServerStreamingClient[chats.MessageEventRes], error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StreamMessagesForUser", varargs...)
	ret0, _ := ret[0].(grpc.ServerStreamingClient[chats.MessageEventRes])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamMessagesForUser indicates an expected call of StreamMessagesForUser.
func (mr *MockMessageServiceClientMockRecorder) StreamMessagesForUser(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamMessagesForUser", reflect.TypeOf((*MockMessageServiceClient)(nil).StreamMessagesForUser), varargs...)
}
