// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2025_2_Undefined/internal/transport/generated/user (interfaces: UserServiceClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	user "github.com/go-park-mail-ru/2025_2_Undefined/internal/transport/generated/user"
	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockUserServiceClient is a mock of UserServiceClient interface.
type MockUserServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceClientMockRecorder
}

// MockUserServiceClientMockRecorder is the mock recorder for MockUserServiceClient.
type MockUserServiceClientMockRecorder struct {
	mock *MockUserServiceClient
}

// NewMockUserServiceClient creates a new mock instance.
func NewMockUserServiceClient(ctrl *gomock.Controller) *MockUserServiceClient {
	mock := &MockUserServiceClient{ctrl: ctrl}
	mock.recorder = &MockUserServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserServiceClient) EXPECT() *MockUserServiceClientMockRecorder {
	return m.recorder
}

// CreateContact mocks base method.
func (m *MockUserServiceClient) CreateContact(arg0 context.Context, arg1 *user.CreateContactReq, arg2 ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateContact", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateContact indicates an expected call of CreateContact.
func (mr *MockUserServiceClientMockRecorder) CreateContact(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateContact", reflect.TypeOf((*MockUserServiceClient)(nil).CreateContact), varargs...)
}

// GetContacts mocks base method.
func (m *MockUserServiceClient) GetContacts(arg0 context.Context, arg1 *user.GetContactsReq, arg2 ...grpc.CallOption) (*user.GetContactsRes, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetContacts", varargs...)
	ret0, _ := ret[0].(*user.GetContactsRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContacts indicates an expected call of GetContacts.
func (mr *MockUserServiceClientMockRecorder) GetContacts(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContacts", reflect.TypeOf((*MockUserServiceClient)(nil).GetContacts), varargs...)
}

// GetUserAvatars mocks base method.
func (m *MockUserServiceClient) GetUserAvatars(arg0 context.Context, arg1 *user.GetUserAvatarsReq, arg2 ...grpc.CallOption) (*user.GetUserAvatarsRes, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUserAvatars", varargs...)
	ret0, _ := ret[0].(*user.GetUserAvatarsRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAvatars indicates an expected call of GetUserAvatars.
func (mr *MockUserServiceClientMockRecorder) GetUserAvatars(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAvatars", reflect.TypeOf((*MockUserServiceClient)(nil).GetUserAvatars), varargs...)
}

// GetUserById mocks base method.
func (m *MockUserServiceClient) GetUserById(arg0 context.Context, arg1 *user.GetUserByIdReq, arg2 ...grpc.CallOption) (*user.GetUserByIdRes, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUserById", varargs...)
	ret0, _ := ret[0].(*user.GetUserByIdRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserById indicates an expected call of GetUserById.
func (mr *MockUserServiceClientMockRecorder) GetUserById(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserById", reflect.TypeOf((*MockUserServiceClient)(nil).GetUserById), varargs...)
}

// GetUserByPhone mocks base method.
func (m *MockUserServiceClient) GetUserByPhone(arg0 context.Context, arg1 *user.GetUserByPhoneReq, arg2 ...grpc.CallOption) (*user.GetUserByPhoneRes, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUserByPhone", varargs...)
	ret0, _ := ret[0].(*user.GetUserByPhoneRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByPhone indicates an expected call of GetUserByPhone.
func (mr *MockUserServiceClientMockRecorder) GetUserByPhone(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByPhone", reflect.TypeOf((*MockUserServiceClient)(nil).GetUserByPhone), varargs...)
}

// GetUserByUsername mocks base method.
func (m *MockUserServiceClient) GetUserByUsername(arg0 context.Context, arg1 *user.GetUserByUsernameReq, arg2 ...grpc.CallOption) (*user.GetUserByUsernameRes, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUserByUsername", varargs...)
	ret0, _ := ret[0].(*user.GetUserByUsernameRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockUserServiceClientMockRecorder) GetUserByUsername(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockUserServiceClient)(nil).GetUserByUsername), varargs...)
}

// UpdateUserInfo mocks base method.
func (m *MockUserServiceClient) UpdateUserInfo(arg0 context.Context, arg1 *user.UpdateUserInfoReq, arg2 ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateUserInfo", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserInfo indicates an expected call of UpdateUserInfo.
func (mr *MockUserServiceClientMockRecorder) UpdateUserInfo(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserInfo", reflect.TypeOf((*MockUserServiceClient)(nil).UpdateUserInfo), varargs...)
}

// UploadUserAvatar mocks base method.
func (m *MockUserServiceClient) UploadUserAvatar(arg0 context.Context, arg1 *user.UploadUserAvatarReq, arg2 ...grpc.CallOption) (*user.UploadUserAvatarRes, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UploadUserAvatar", varargs...)
	ret0, _ := ret[0].(*user.UploadUserAvatarRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadUserAvatar indicates an expected call of UploadUserAvatar.
func (mr *MockUserServiceClientMockRecorder) UploadUserAvatar(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadUserAvatar", reflect.TypeOf((*MockUserServiceClient)(nil).UploadUserAvatar), varargs...)
}
